config/routes.rb
Rails.application.routes.draw do
  resources :rooms, param: :name
  resources :single_messages

  mount ActionCable.server => '/cable'

  namespace "admin" do
    get "/dashboard" => "dashboards#dashboard"
    get "/logs" => "dashboards#logs"
    get '/import_file' => 'dashboards#import_file'
    post '/import' => 'dashboards#import'
    get "/reported_messages" => "dashboards#reported_messages"
    get "/send_message" => "dashboards#send_message"
    get "/delete_message/:id" => "dashboards#delete_message"
    get "/broadcast_message" => "dashboards#broadcast_message"
    get '/profile/:id' => "dashboards#profile"
    get '/change_role/:id' => "dashboards#change_role"
    post '/block_unblock' => 'dashboards#block_unblock'
    post '/change_category' => 'dashboards#change_category'
    get '/messages' => 'dashboards#messages'
    get '/refresh_messages' => 'dashboards#refresh_messages'
    resources :available_categories
  end

  post '/admin/create' => 'rooms#admin_create'
  get '/profile' => 'users#profile'
  patch "/users/:id" => 'users#update', as: :update
  post '/users/feedback' => 'users#feedback'
  get 'messages/index'
  get '/accept/:id' => 'single_messages#accept'
  get '/reject/:id' => 'single_messages#reject'
  get '/refresh_header' => 'users#refresh_header'
  post '/messages' => "messages#post_message"
  post '/messages/report' => "messages#report"
  post '/messages/like' => "messages#like"
  post '/reply' => "messages#post_reply"
  get '/personal_chats/:id' => 'single_messages#personal_chats'

  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations'}, path: '', path_names: {sign_in: 'login', sign_up: 'register'}

  root to: "messages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_one :chat_room, dependent: :destroy
	has_many :messages, foreign_key: "sender_id", class_name: "Message", dependent: :destroy
	has_many :replies, foreign_key: "sender_id", class_name: "Reply", dependent: :destroy
	has_many :logs, foreign_key: "sender_id", class_name: "Log", dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :matchers, dependent: :destroy
  has_many :single_messages, dependent: :destroy
  has_many :rooms, through: :single_messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  as_enum :role, admin: 0, user: 1, manager: 2     

  validates_presence_of :name, :location, :education, :gender, :on => :update       
  after_create :create_room
  before_update :set_points
  scope :users, -> { where(role_cd: 1) }

  def set_points
  	points = 0
  	if self.location.present?
  		points+= 10
  	end
  	if self.education.present?
  		points+= 5
  	end
  	if self.gender.present?
  		points+= 5
  	end
  	if self.name.present?
  		points+= 5
  	end
  	self.score = points
  end

  def admin?
    role == :admin
  end

  def manager?
    role == :manager
  end

  def add_loyalty_score(points)
    if self.loyalty_score.nil?
      score = 0
    else
      score = self.loyalty_score + points
    end
    self.update_attributes(loyalty_score: score)
  end

  def add_messaging_score(points)
    if self.messaging_score.nil?
      score = 0
    else
      score = self.messaging_score + points
    end
    self.update_attributes(messaging_score: score)
  end

  def minus_messaging_score(points)
    if self.messaging_score.nil? or self.messaging_score == 0 or self.messaging_score <= 20
      score = 0
    else
      score = self.messaging_score - points
    end
    self.update_attributes(messaging_score: score)
  end

  def minus_loyalty_score(points)
    if self.loyalty_score.nil? or self.loyalty_score == 0 or self.loyalty_score <= 20
      score = 0
    else
      score = self.loyalty_score - points
    end
    self.update_attributes(loyalty_score: score)
  end

  def create_room
		ChatRoom.create(user_id: self.id)
	end

  def add_flag_point
    if self.flagged.nil?
      self.flagged = 1
    else  
      self.flagged += 1
    end
    self.save
  end

  def minus_flag_point
    self.flagged -= 1
    self.save
  end

  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    # user.image = auth.info.image
	    user.gender = auth.info.gender
	    user.age_range = auth.info.age_range
      user.confirmed_at = Time.now
	    # assuming the user model has an image
	    # If you are using confirmable and the provider(s) you use validate emails, 
	    # uncomment the line below to skip the confirmation emails.
	    user.skip_confirmation!
	  end
	end
   
	
	def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end    
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  # View profile
  def profile
  	@user = current_user
  end

  # update profile
  def update
  	@user = User.find(params[:id])
  	@user.complete_profile = true
  	respond_to do |format|
	  	if @user.update(user_params)
	      format.html { redirect_to root_path, notice: 'User was successfully updated.' }
	    else
	      format.html { render :profile }
	    end
	  end
  end

  def refresh_header
    respond_to do |format|
      format.js
    end
  end

  # submit feedback
  def feedback
    if params[:rating].present? && params[:message].present?
      feed = Feedback.new
      feed.user = current_user
      feed.rating = params[:rating]
      feed.message = params[:message]
      feed.save
      ApplicationMailer.send_feedback(feed).deliver_now
    end
    redirect_to request.referer, notice: "Feedback saved!"
  end

  private
  def user_params
    params.require(:user).permit(:name, :location, :education, :gender, :coordinates, :city, :area, :state, :country, :country_code, :date_of_birth, :college)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Update Profile</h3>
  </div><!-- /.box-header -->
  <!-- form start -->
  <%= form_for(@user, url: update_path(@user), method: :patch) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> 
    <h2>Error!</h2>

    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="box-body">
    <div class="form-group">
      <label>Name* </label>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
    </div>
    <div class="form-group">
      <label>Location* </label>
      <%= f.text_field :location, class: "form-control", placeholder: "Enter a location" %>
    </div>
    <div class="form-group" id="test">
      <label>Date of Birth* </label>
      <%= f.text_field :date_of_birth, class: "form-control", placeholder: "Date of birth", "data-date-format"=>"mm/dd/yyyy", id: "thedate", required: true %>
    </div>
    <div class="form-group">
      <label>City* </label>
      <%= f.text_field :city, class: "form-control", placeholder: "City", required: true %>
    </div>
    <div class="form-group">
      <label>University/College* </label>
      <%= f.select :college, options_for_select(["GIFT", "COMSATS", "FAST", "NUST", "LUMS","BNU","LSE","GIKI", "UMT", "Other"], @user.college), {include_blank: "Please select your University"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Education* </label>
      <%= f.select :education, options_for_select(["School", "High School", "College", "University", "Other"], @user.education), {include_blank: "Please select an education level"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label for="exampleInputFile">Gender* </label>
      <%= f.select :gender, options_for_select(["Male", "Female"], @user.gender), {include_blank: "Please select a gender"}, {class: "form-control"} %>
    </div>
  </div><!-- /.box-body -->
  <%= f.hidden_field :coordinates, data: {geo: "location"} %>
  <%= f.hidden_field :city, data: {geo: "locality"} %>
  <%= f.hidden_field :area, data: {geo: "sublocality"} %>
  <%= f.hidden_field :state, data: {geo: "administrative_area_level_1"} %>
  <%= f.hidden_field :country, data: {geo: "country"} %>
  <%= f.hidden_field :country_code, data: {geo: "country_short"} %>
  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
  <% end %>    
</div>


<script type="text/javascript">
  $("#user_location").geocomplete({
    details: "form",
    detailsAttribute: "data-geo",
    types: ["geocode", "establishment"],
  });
  $('#user_date_of_birth').datepicker({
      format: 'yyyy-mm-dd',
      container:'#test',
      autoclose: true,
      orientation: "auto",
      startView: 'decades'
    });
</script>

<style>
  body{
    min-height: auto;
  }
</style>

app/views/users/refresh_header.js.erb
$('#header').html("<%= j render(:partial => 'layouts/header') %>");