config/routes.rb
Rails.application.routes.draw do
  resources :rooms, param: :name
  resources :single_messages

  mount ActionCable.server => '/cable'

  namespace "admin" do
    get "/dashboard" => "dashboards#dashboard"
    get "/logs" => "dashboards#logs"
    get '/import_file' => 'dashboards#import_file'
    post '/import' => 'dashboards#import'
    get "/reported_messages" => "dashboards#reported_messages"
    get "/send_message" => "dashboards#send_message"
    get "/delete_message/:id" => "dashboards#delete_message"
    get "/broadcast_message" => "dashboards#broadcast_message"
    get '/profile/:id' => "dashboards#profile"
    get '/change_role/:id' => "dashboards#change_role"
    post '/block_unblock' => 'dashboards#block_unblock'
    post '/change_category' => 'dashboards#change_category'
    get '/messages' => 'dashboards#messages'
    get '/refresh_messages' => 'dashboards#refresh_messages'
    resources :available_categories
  end

  post '/admin/create' => 'rooms#admin_create'
  get '/profile' => 'users#profile'
  patch "/users/:id" => 'users#update', as: :update
  post '/users/feedback' => 'users#feedback'
  get 'messages/index'
  get '/accept/:id' => 'single_messages#accept'
  get '/reject/:id' => 'single_messages#reject'
  get '/refresh_header' => 'users#refresh_header'
  post '/messages' => "messages#post_message"
  post '/messages/report' => "messages#report"
  post '/messages/like' => "messages#like"
  post '/reply' => "messages#post_reply"
  get '/personal_chats/:id' => 'single_messages#personal_chats'

  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations'}, path: '', path_names: {sign_in: 'login', sign_up: 'register'}

  root to: "messages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :single_messages, dependent: :destroy
  # has_many :users, through: :messages
  validates :title, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :set_name

  def to_param
    self.name
  end

  def set_name
    self.name = self.title.downcase.gsub(" ", "-")
  end

  def sanitize
    self.title = self.title.strip
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    if request.referrer.split("/").last == "chatrooms"
      flash[:notice] = nil
    end
    @room = Room.new
  end

  # Create personal chat room
  def create
    @room = Room.find_or_create_by(room_params)
    @room.user = current_user
    msg = Reply.find_by(id: params[:message_id])
    @room.chat_with = msg.sender.id
    msg.sender.add_messaging_score(30)
    @user = msg.sender
    @room.save
  end

  # Create personal chat room with admin
  def admin_create
    @room = Room.find_or_create_by(room_params)
    @room.user = current_user
    if params[:user_id].present?
      @user = User.find_by(id: params[:user_id])
      @room.chat_with = @user.id
    else
      msg = Message.find_by(id: params[:message_id])
      @room.chat_with = msg.sender.id
      msg.sender.add_messaging_score(30)
      @user = msg.sender
    end
    @room.save
    respond_to do |format|
      format.js { render "rooms/create.js.erb" }
    end
  end

  def index
    @room = Room.new
    @rooms = Room.all
  end

  def show
    @room = Room.find_by(name: params[:name])
    @message = SingleMessage.new
  end

  private

  def room_params
    params.require(:room).permit(:title)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<li><%= link_to room.title, room_path(room) %></li>

app/views/rooms/_room_form.html.erb
<div class="room-form">
  <%= form_for room, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">title:</span>
      <%= f.text_field :title, class: "form-control"%>
    </div>
    <%= f.submit class: "btn btn-primary", id: "create-room" %>
  <% end %>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/create.js.erb
window.location.href = "/personal_chats/<%= @room.id %>";

app/views/rooms/destroy.html.erb
<h1>Rooms#destroy</h1>
<p>Find me in app/views/rooms/destroy.html.erb</p>

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="room-title">
  <h1>Rooms</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="rooms">
  <%= render partial: 'room_form', locals: {room: @room} %>
  <div id="room-errors">
    
  </div>
    <ul id="room-index"> 
  <% if @rooms.any? %>
      <%= render @rooms%>
  <%else %>
    </ul>
    <p>Crete a room!</p>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">

  <h1>Create a Room on a programming title</h1>
    <div class="well">
      <div class="room-form">
        <%= form_for @room do |f| %>
          <div class="input-group">
            <span class="input-group-addon">title:</span>
            <%= f.text_field :title, class: "form-control"%>
          </div>
          <%= f.submit class: "btn btn-primary", id: "create-room" %>
        <% end %>
      </div>
    </div>

    <%= render partial: 'layouts/flash_errors'%>
</div>

app/views/rooms/room_error.js.erb
$("input#room_topic").val(" ");
$("#room-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/rooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @room.title %></h1>

<div class="panel panel-default">
  <% if @room.single_messages.any? %>
    <div class="panel-body" id="messages">
      <%= render partial: 'single_messages/single_message', collection: @room.single_messages%>
    </div>
  <%else%>
    <div class="panel-body hidden" id="messages">
    </div>
  <%end%>
</div>

  <%= render partial: 'single_messages/single_message_form', locals: {message: @message, room: @room}%>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>