config/routes.rb
Rails.application.routes.draw do
  resources :rooms, param: :name
  resources :single_messages

  mount ActionCable.server => '/cable'

  namespace "admin" do
    get "/dashboard" => "dashboards#dashboard"
    get "/logs" => "dashboards#logs"
    get '/import_file' => 'dashboards#import_file'
    post '/import' => 'dashboards#import'
    get "/reported_messages" => "dashboards#reported_messages"
    get "/send_message" => "dashboards#send_message"
    get "/delete_message/:id" => "dashboards#delete_message"
    get "/broadcast_message" => "dashboards#broadcast_message"
    get '/profile/:id' => "dashboards#profile"
    get '/change_role/:id' => "dashboards#change_role"
    post '/block_unblock' => 'dashboards#block_unblock'
    post '/change_category' => 'dashboards#change_category'
    get '/messages' => 'dashboards#messages'
    get '/refresh_messages' => 'dashboards#refresh_messages'
    resources :available_categories
  end

  post '/admin/create' => 'rooms#admin_create'
  get '/profile' => 'users#profile'
  patch "/users/:id" => 'users#update', as: :update
  post '/users/feedback' => 'users#feedback'
  get 'messages/index'
  get '/accept/:id' => 'single_messages#accept'
  get '/reject/:id' => 'single_messages#reject'
  get '/refresh_header' => 'users#refresh_header'
  post '/messages' => "messages#post_message"
  post '/messages/report' => "messages#report"
  post '/messages/like' => "messages#like"
  post '/reply' => "messages#post_reply"
  get '/personal_chats/:id' => 'single_messages#personal_chats'

  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations'}, path: '', path_names: {sign_in: 'login', sign_up: 'register'}

  root to: "messages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::AppController
  skip_before_action :admin_restricted, only: :profile
  # layout "application", only: [:messages]

  # lists users
  def dashboard
    @search = UserSearch.new(params)
    @users = @search.result.where.not(:role_cd => 0).paginate(page: params[:page], per_page: 25)
  end

  # messages logs
  def logs
    @logs = Log.where(log_type: "message").order("created_at desc").last(100)
  end

  # messages view where admin can reply
  def messages
    @messages = Message.order("id desc").first(20)
    @user = current_user
    render layout: "application"
  end

  # add / change message category
  def change_category
    @message = Message.find(params[:message_id])
    category = AvailableCategory.find_by(name: params[:category])
    @message.available_category = category
    @message.save
    respond_to do |format|
      format.js
    end
  end

  def refresh_messages
    @messages = Message.order("id desc").first(20)
    @user = current_user
    respond_to do |format|
      format.js
    end
  end

  # change user role
  def change_role
    @user = User.find(params[:id])
    if @user.role == :user
      role = :manager
    else
      role = :user
    end
    @user.update_attributes(:role => role)
    respond_to do |format|
      format.js
    end
  end

  # import abuse filter file
  def import
    AbuseFilter.import(params[:file])
    redirect_to request.referer, notice: "File imported."
  end

  def import_file
  end

  # block / unblock users
  def block_unblock
    user = User.find_by(:id => params[:user_id])
    if user.blocked
      block = false
    else
      block = true
    end
    user.update_attributes(:blocked => block)
    redirect_to admin_dashboard_path, notice: block ? "Successfully Blocked" : "Successfully Unblocked!"
  end

  def broadcast_message
  end

  # broadcast message to 3wrongs users
  def send_message
    @message = Message.create(content: params[:message], sender_id: current_user.id)
    User.all.each do |user|
      user.chat_room.messages << @message
      BroadcastAllJob.perform_now(user, @message, user.chat_room.id)
    end
    redirect_to request.referer
  end

  # view reported messages
  def reported_messages
    @messages = ReportedMessage.get_messages
  end

  def delete_message
    if params[:id].present?
      msg = Message.find_by_id(params[:id])
      msg.destroy if msg.present?
    end
    redirect_to request.referer, notice: "Successfully Deleted!"
  end

  def profile
    @user = User.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/admin/dashboards/_log_message.html.erb
<div style="margin-left: 10px;">
	<span class='reply-text'>
		<strong><%= message.sender.email %>:</strong> <%= message.content %>
	</span>
	<span class='text-muted pull-right'><%= message.created_at.strftime("%d %b %l:%M %P ") %></span>
</div>
</br>

app/views/admin/dashboards/_messages.html.erb
<% @messages.group_by{|x| x.created_at.strftime("%A %d %B, %Y")}.each do |key, messages| %>
    <div class="conservation-time">
        <%= key %>
    </div>
    <% messages.each do |message| %>
        <% if message.sender.role_cd == 0 %>
            <div class="message received">
                <span class="pull-left-width">
          <span>Hello, <%= @user.email %></span>
                <br>
                <%= message.content %>
                    <br/>
                    <span>Thank you!</span>
                    </span>
                    <span class="metadata">
          <span class="time"><%= message.created_at.strftime(" %l:%M %P ") %></span>
                    </span>
            </div>
            <% else %>
                <div class="message received" id="received<%= message.id %>">
                    <span class="pull-left-width">
          <%= message.content %>
        </span>
                    <% reply = message.replies.where(sender_id: @user.id).first %>
                        <% if reply.present? %>
                            <div class="reply-message">
                                <span class="pull-left-width"><%= reply.content %></span>
                                <span class="metadata">
                <span class="time"><%= reply.created_at.strftime("%l:%M %P ") %></span>
                                </span>
                            </div>
                            <%else%>
                                <div class="direct-chat-text reciever-message">
                                    <a href="javascript:void(0)" id="<%= message.id %>-<%= @user.id %>" class="reply-btn">Reply</a>
                                    <a href="javascript:void(0)" id="<%= message.id %>-<%= @user.id %>-cancel" class="cancel-btn hidden">Cancel</a>
                                    <div class="row reply-box hidden" id="reply-<%= message.id %>-<%= @user.id %>">
                                        <%= form_tag("/reply", method: 'post', :remote => true, class: "form-horizontal") do %>
                                            <div class="col-xs-12">
                                                <input type="text" name="reply" id="reply" placeholder="Type Message ..." class="form-control">
                                                <input type="hidden" name="message_id" value="<%= message.id %>">
                                            </div>
                                            <div class="col-xs-12">
                                                <button type="submit" class="btn btn-primary btn-flat custom-float">Send</button>
                                            </div>
                                            <% end %>
                                    </div>
                                </div>
                                <%end%>
                                    <div class="metadata-1">
                                        <div class="cat-left category-<%= message.id %>">
                                            <a href="#" class="category-ch" id="<%= message.id %>" data-toggle="modal" data-target="#changeCat">
              <span class="label label-warning" data-toggle="tooltip" title="<%= message.available_category.try(:name).try(:titleize) %>" style="background-color: <%= category(message.available_category.try(:name)).try(:color) %> !important;"><i class="<%= category(message.available_category.try(:name)).present? ? category(message.available_category.try(:name)).try(:icon) : 'fa fa-question-circle-o' %>"></i></span>
            </a>
                                        </div>
                                        <div class="cat-right">
                                            <%= link_to "<span class='fa fa-user'></span>".html_safe, "/admin/profile/#{message.sender.id}", {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#profileModal', :class => "btn btn-sm btn-primary"} %>
                                        </div>
                                        <div class="cat-right">
                                            <%= link_to "<span class='fa fa-comments'></span>".html_safe, "javascript:void(0)", {:class => "btn btn-sm btn-primary start-chat", id: "#{message.id}"} %>
                                        </div>
                                    </div>
                                    <span class="metadata">
          <span class="time"><%= message.created_at.strftime(" %l:%M %P ") %></span>
                                    </span>
                </div>
                <% end %>
                    <% end %>
                        <% end %>

                            <div id="profileModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                                <div class="modal-dialog">

                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title"><i class="fa fa-user margin-r-5"></i>User Profile</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="user-profile">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div id="changeCat" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                                <div class="modal-dialog">

                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title"><i class="fa fa-user margin-r-5"></i>Categories</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="maxl">
                                                <%= form_tag("/admin/change_category", method: 'post', :remote => true) do %>
                                                    <% AvailableCategory.all.each do |ac| %>
                                                        <label class="radio inline"> 
            <input type="radio" name="category" value="<%= ac.name %>" checked>
            <span style="color:<%= ac.color %>;"> <i class="<%= ac.icon %>"></i> <%= ac.name.titleize %></span> 
          </label>
                                                        <% end %>
                                                            <input type="hidden" name="message_id" class="chCat">
                                                            <p class="s-btn">
                                                                <input type="submit" value="Change" class="btn btn-default">
                                                            </p>
                                                            <% end %>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <style type="text/css">
                                .direct-chat-text {
                                    float: left;
                                    width: 100%;
                                    margin: 8px 0px;
                                }
                                
                                .maxl {
                                    width: 100%;
                                    float: left;
                                    padding: 20px
                                }
                                
                                .maxl label {
                                    float: left;
                                    width: auto;
                                    min-width: 200px;
                                    position: inherit;
                                }
                                
                                .s-btn {
                                    float: left;
                                    width: 100%;
                                }
                            </style>
                            <script type="text/javascript">
                                function refreshPartial() {
                                    $.ajax({
                                        url: "/admin/refresh_messages"
                                    })
                                }
                                $(".form-horizontal").on("submit", function() {
                                    setTimeout(function() {
                                        refreshPartial();
                                    }, 1000);
                                });

                                $(".start-chat").click(function() {
                                    var message_id = $(this).attr("id");
                                    title = message_id
                                    $.ajax({
                                            method: "POST",
                                            url: "/admin/create.js",
                                            data: jQuery.param({
                                                room: {
                                                    title: title
                                                },
                                                message_id: message_id
                                            })
                                        })
                                        .done(function(msg) {
                                            setTimeout(function() {
                                                refreshPartial();
                                            }, 1000);
                                        });
                                });

                                $('#changeCat').appendTo("body");
                                $('#profileModal').appendTo("body");
                                $(".category-ch").click(function() {
                                    $(".chCat").val($(this).attr("id"));
                                });
                                $(".reply-btn").click(function() {
                                    var id = $(this).attr("id");
                                    $("#reply-" + id).removeClass("hidden");
                                    $("#" + id + "-cancel").removeClass("hidden");
                                    $("#" + id).addClass("hidden");
                                })
                                $(".cancel-btn").click(function() {
                                    var id = $(this).attr("id").split("-cancel")[0];
                                    $("#reply-" + id).addClass("hidden");
                                    $("#" + id + "-cancel").addClass("hidden");
                                    $(".reply-btn#" + id).removeClass("hidden");
                                });
                            </script>

app/views/admin/dashboards/change_role.js.erb
$(".role-<%= @user.id %>").html("<%= @user.role.to_s.titleize %>");

app/views/admin/dashboards/dashboard.html.erb
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Dashboard
      <small>Preview</small>
    </h1>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Users</h3>
          </div>
          <div class="users-filters">
            <strong>Filters</strong>
            <div class="row">
              <div class="col-md-12" style="margin-bottom: 10px;">
                <form action="/admin/dashboard" accept-charset="UTF-8" method="get">
                  <input name="utf8" type="hidden" value="✓">
                  <div>
                    <input class="form-control" type="search" name="search[email]" value="<%= params[:search].try(:[], :email) %>" placeholder="Email search ...">
                  </div>
                </form>
              </div>
            </div>
            <div class="row">
              <div class="col-md-4" style="margin-bottom: 10px;">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                  <% @education_filter = @search.filter(:education) %>
                  <%= @education_filter.name.titleize %>
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <% @education_filter.facet.reject(&:selected).each do |facet_value| %>
                      <% entity = facet_value.entity %>
                      <% display = entity %>
                      <li>
                        <%= link_to(@education_filter.add(entity).path, class: "add-filter") do %>
                          <span class="education-name"><%= display %></span>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
              <div class="col-md-4" style="margin-bottom: 10px;">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                  <% @age_range_filter = @search.filter(:age_range) %>
                  <%= @age_range_filter.name.titleize %>
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <% @age_range_filter.facet.reject(&:selected).each do |facet_value| %>
                      <% entity = facet_value.entity %>
                      <% display = entity %>
                      <li>
                        <%= link_to(@age_range_filter.add(entity).path, class: "add-filter") do %>
                          <span class="age_range-name"><%= display %></span>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
              <div class="col-md-4" style="margin-bottom: 10px;">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                  <% @gender_filter = @search.filter(:gender) %>
                  <%= @gender_filter.name.titleize %>
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <% @gender_filter.facet.reject(&:selected).each do |facet_value| %>
                      <% entity = facet_value.entity %>
                      <% display = entity %>
                      <li>
                        <%= link_to(@gender_filter.add(entity).path, class: "add-filter") do %>
                          <span class="gender-name"><%= display %></span>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6" style="margin-bottom: 10px;">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                  <% @location_filter = @search.filter(:location) %>
                  <%= @location_filter.name.titleize %>
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <% @location_filter.facet.reject(&:selected).each do |facet_value| %>
                      <% entity = facet_value.entity %>
                      <% display = entity %>
                      <li>
                        <%= link_to(@location_filter.add(entity).path, class: "add-filter") do %>
                          <span class="location-name"><%= display %></span>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
              <div class="col-md-6" style="margin-bottom: 10px;">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                  <% @city_filter = @search.filter(:city) %>
                  <%= @city_filter.name.titleize %>
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <% @city_filter.facet.reject(&:selected).each do |facet_value| %>
                      <% entity = facet_value.entity %>
                      <% display = entity %>
                      <li>
                        <%= link_to(@city_filter.add(entity).path, class: "add-filter") do %>
                          <span class="city-name"><%= display %></span>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="selected-filters">
            <strong>Selected Filters:</strong>
            <div class="row">
              <div class="col-md-4">
                <% @education_filter = @search.filter(:education) %>
                <% @education_filter.selected.each do |entity| %>
                  <% display = entity %>
                  <div class="currently-box">
                    <%= link_to @education_filter.remove(entity).path do %>
                      <strong>Education:</strong> <%= display %> <i class="fa fa-times-circle-o pull-right" aria-hidden="true"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div class="col-md-4">
                <% @age_range_filter = @search.filter(:age_range) %>
                <% @age_range_filter.selected.each do |entity| %>
                  <% display = entity %>
                  <div class="currently-box">
                    <%= link_to @age_range_filter.remove(entity).path do %>
                      <strong>Age Range:</strong> <%= display %> <i class="fa fa-times-circle-o pull-right" aria-hidden="true"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div class="col-md-4">
                <% @gender_filter = @search.filter(:gender) %>
                <% @gender_filter.selected.each do |entity| %>
                  <% display = entity %>
                  <div class="currently-box">
                    <%= link_to @gender_filter.remove(entity).path do %>
                      <strong>Gender:</strong> <%= display %> <i class="fa fa-times-circle-o pull-right" aria-hidden="true"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <% @location_filter = @search.filter(:location) %>
                <% @location_filter.selected.each do |entity| %>
                  <% display = entity %>
                  <div class="currently-box">
                    <%= link_to @location_filter.remove(entity).path do %>
                      <strong> Location: </strong> <%= display %> <i class="fa fa-times-circle-o pull-right" aria-hidden="true"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div class="col-md-6">
                <% @city_filter = @search.filter(:city) %>
                <% @city_filter.selected.each do |entity| %>
                  <% display = entity %>
                  <div class="currently-box">
                    <%= link_to @city_filter.remove(entity).path do %>
                      <strong> City: </strong> <%= display %> <i class="fa fa-times-circle-o pull-right" aria-hidden="true"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="box-body table-responsive no-padding user-table">
            <table class="table table-hover">
              <tr>
                <!-- <th>ID</th> -->
                <th>Email</th>
                <th>Location</th>
                <th>City</th>
                <th>Education</th>
                <th>Gender</th>
                <th>Age Range</th>
                <th>Status</th>
                <th>Role</th>
                <th>Actions</th>
                <th>Block/Unblock</th>
              </tr>
              <% @users.each do |user| %>
                <tr>
                  <!-- <td><%= user.id %></td> -->
                  <td><%= user.email %></td>
                  <td><%= user.location %></td>
                  <td><%= user.city %></td>
                  <td><%= user.education %></td>
                  <td><%= user.gender %></td>
                  <td><%= user.age_range %></td>
                  <td>
                    <span class="users-<%= user.id %>-online <%= user.is_online? == true ? '' : 'hidden' %> label label-success">Online</span>
                    <span class="users-<%= user.id %>-offline <%= user.is_online? == false ? '' : 'hidden' %> label label-danger">Offline</span>
                  </td>
                  <td class="role-<%= user.id %>"><%= user.role.to_s.titleize %></td>
                  <td>
                    <%= link_to "View Profile", "/admin/profile/#{user.id}", {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#profileModal', :class => "btn btn-sm btn-primary custom-primary"} %>
                    <%= link_to "Change Role", "/admin/change_role/#{user.id}", {:remote => true, :class => "btn btn-sm btn-primary custom-primary"} %>
                    <a href="javascipt:void(0)" data-toggle="tooltip" title="Start Conversation ?" class="start-chat btn btn-default" id="user_<%= user.id %>">Start Chat</a>
                  </td>
                  <td>
                    <%= form_tag(admin_block_unblock_path, method: "post") do %>
                      <% if user.blocked %>
                        <input type="hidden" value="<%= user.id %>" name="user_id"  />
                        <button type="submit" class="btn btn-default" >Unblock</button>
                      <% else %>
                        <input type="hidden" value="<%= user.id %>" name="user_id"  />
                        <button type="submit" class="btn btn-danger" >Block</button>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td colspan="4" class="text-center"><%= will_paginate @users, renderer: BootstrapPagination::Rails %></td>
              </tr>
            </table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div><!-- /.row -->
<!-- Modal -->
  </section>
</div>  

<div id="profileModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><i class="fa fa-user margin-r-5"></i>User Profile</h4>
      </div>
      <div class="modal-body">
        <div class="user-profile">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<style type="text/css">
  .box-widget{
    min-height: 600px;
    max-height: 600px;
    height: 600px;
    overflow: auto;
  }
  .user-table{
    max-height: 560px;
    min-height: 560px;
    height: 560px;
    overflow: auto;
  }
  .users-filters,
  .selected-filters{
    width: 100%;
    height: auto;
    padding: 15px;
  }
  .currently-box{
    border: 1px solid #ccc;
    padding: 5px;
    margin: 5px;
  }
  .btn.dropdown-toggle{
    width: 100%;
  }
  .dropdown-menu{
    width: 100%;
    color: #818181;
  }
</style>

<script type="text/javascript">
  $(".start-chat").click(function() {
    var message_id = $(this).attr("id");
    title = message_id
    $.ajax({
      method: "POST",
      url: "/admin/create.js",
      data: jQuery.param({
        room: {
          title: title
        },
        user_id: message_id.match(/\d+/)
      })
    })
    .done(function(msg) {
      setTimeout(function() {
        refreshPartial();
      }, 1000);
    });
  });
</script>

app/views/admin/dashboards/import_file.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      Import/Update Excel File
    </h1>
  </section>
  <section class="content">
    <div class="container">
			<%= form_tag admin_import_path, multipart: true do %>
			<div class="row">
				<div class="col-md-4">
					<div class="field">
						<%= file_field_tag :file, class: "form-control" %>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="field">
					  <%= submit_tag "Import", class: "btn btn-default" %>
					</div>
				</div>
			</div>		
			<% end %>
		</div>
	</section>
	<div class="row">
		<div class="col-md-12">
			<div class="container">
				<h1>Availble Words:</h1>
				<p><%= AbuseFilter.all.map(&:abuse).join(", ") %></p>
			</div>
		</div>
	</div>
</div>			

app/views/admin/dashboards/profile.js.erb
$(".user-profile").html("<%= j render(:partial => 'admin/dashboards/profile', locals: {user: @user}) %>");

app/views/admin/dashboards/refresh_messages.js.erb
$('.conversation-container.admin').html("<%= j render(:partial => 'messages', locals: { :@messages => @messages, :@user => @user }) %>");