config/routes.rb
Rails.application.routes.draw do
  resources :rooms, param: :name
  resources :single_messages

  mount ActionCable.server => '/cable'

  namespace "admin" do
    get "/dashboard" => "dashboards#dashboard"
    get "/logs" => "dashboards#logs"
    get '/import_file' => 'dashboards#import_file'
    post '/import' => 'dashboards#import'
    get "/reported_messages" => "dashboards#reported_messages"
    get "/send_message" => "dashboards#send_message"
    get "/delete_message/:id" => "dashboards#delete_message"
    get "/broadcast_message" => "dashboards#broadcast_message"
    get '/profile/:id' => "dashboards#profile"
    get '/change_role/:id' => "dashboards#change_role"
    post '/block_unblock' => 'dashboards#block_unblock'
    post '/change_category' => 'dashboards#change_category'
    get '/messages' => 'dashboards#messages'
    get '/refresh_messages' => 'dashboards#refresh_messages'
    resources :available_categories
  end

  post '/admin/create' => 'rooms#admin_create'
  get '/profile' => 'users#profile'
  patch "/users/:id" => 'users#update', as: :update
  post '/users/feedback' => 'users#feedback'
  get 'messages/index'
  get '/accept/:id' => 'single_messages#accept'
  get '/reject/:id' => 'single_messages#reject'
  get '/refresh_header' => 'users#refresh_header'
  post '/messages' => "messages#post_message"
  post '/messages/report' => "messages#report"
  post '/messages/like' => "messages#like"
  post '/reply' => "messages#post_reply"
  get '/personal_chats/:id' => 'single_messages#personal_chats'

  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", confirmations: 'confirmations'}, path: '', path_names: {sign_in: 'login', sign_up: 'register'}

  root to: "messages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/available_category.rb
class AvailableCategory < ApplicationRecord
  belongs_to :message
end

app/controllers/admin/available_categories_controller.rb
class Admin::AvailableCategoriesController < Admin::AppController
  before_action :set_available_category, only: [:show, :edit, :update, :destroy]

  # GET /available_categories
  # GET /available_categories.json
  def index
    @available_categories = AvailableCategory.all
  end

  # GET /available_categories/1
  # GET /available_categories/1.json
  def show
  end

  # GET /available_categories/new
  def new
    @available_category = AvailableCategory.new
  end

  # GET /available_categories/1/edit
  def edit
  end

  # POST /available_categories
  # POST /available_categories.json
  def create
    @available_category = AvailableCategory.new(available_category_params)

    respond_to do |format|
      if @available_category.save
        format.html { redirect_to admin_available_categories_path, notice: 'Available category was successfully created.' }
        format.json { render :show, status: :created, location: @available_category }
      else
        format.html { render :new }
        format.json { render json: @available_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /available_categories/1
  # PATCH/PUT /available_categories/1.json
  def update
    respond_to do |format|
      if @available_category.update(available_category_params)
        format.html { redirect_to admin_available_categories_path, notice: 'Available category was successfully updated.' }
        format.json { render :show, status: :ok, location: @available_category }
      else
        format.html { render :edit }
        format.json { render json: @available_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /available_categories/1
  # DELETE /available_categories/1.json
  def destroy
    @available_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_available_categories_path, notice: 'Available category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_available_category
      @available_category = AvailableCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def available_category_params
      params.require(:available_category).permit(:name, :color, :icon)
    end
end

app/helpers/available_categories_helper.rb
module AvailableCategoriesHelper
end

app/views/admin/available_categories/_form.html.erb
<%= form_for([:admin, @available_category]) do |f| %>
  <% if @available_category.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @available_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-4">
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true, placeholder: "Entertainment" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <div class="field">
        <%= f.label :color %>
        <%= f.text_field :color, class: "form-control", required: true, placeholder: "#AAAAAA" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <div class="field">
        <%= f.label :icon %>
        <%= f.text_field :icon, class: "form-control", required: true, placeholder: "fa fa-plus" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <div class="field">
        <%= f.submit class: "btn btn-default" %>
      </div>
    </div>  
  </div>  
<% end %>

app/views/admin/available_categories/edit.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>Edit Category</h1>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
      	<div class="box">
          <div class="users-filters">
            <div class="row">
              <div class="col-md-12" style="margin-bottom: 10px;">
      					<%= render 'form' %>
      				</div>
      			</div>
      		</div>
      	</div>				
      </div>
    </div>
  </section>
</section>      	

app/views/admin/available_categories/index.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>Available Categories</h1>
  </section>
  <section class="content">
    <%= link_to 'Add new Category', new_admin_available_category_path, class: "btn btn-primary" %>
    <div class="row">
      <div class="col-xs-12">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Color</th>
                <th>Icon</th>
                <th colspan="2">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @available_categories.each do |available_category| %>
                <tr>
                  <td><%= available_category.name %></td>
                  <td><%= available_category.color %></td>
                  <td><%= available_category.icon %></td>
                  <td><%= link_to 'Edit', edit_admin_available_category_path(available_category) %></td>
                  <td><%= link_to 'Destroy', admin_available_category_path(available_category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>  
</div>

app/views/admin/available_categories/new.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>New Categories</h1>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
      	<div class="box">
          <div class="users-filters">
            <div class="row">
              <div class="col-md-12" style="margin-bottom: 10px;">
      					<%= render 'form' %>
      				</div>
      			</div>
      		</div>
      	</div>				
      </div>
    </div>
  </section>
</section>      	

app/views/admin/available_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @available_category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @available_category.color %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @available_category.icon %>
</p>

<%= link_to 'Edit', edit_available_category_path(@available_category) %> |
<%= link_to 'Back', available_categories_path %>